name: new content deploy

on:
  push:
    branches: ["main"]
    paths:
      - public/**

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: configure pages
        uses: actions/configure-pages@v3
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public/'
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v2
